config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "plans#index"

  resources :plans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :title, presence: true, length: {maximum: 20}
  validates :start_date, presence: :true
  validates :finish_date, presence: :true
  validate :greater_than_start_date?
  validates :memo, length: {maximum:500}

  private

  def greater_than_start_date?
    if !(start_date) || !(finish_date)
      return false
    end

    if start_date > finish_date
      errors.add(:finish_date, "終了日は開始日以降の日付で選択してください")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
    @today = Date.today.strftime("%Y/%m/%d")
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(schedule_params)
    if @plan.save
      flash[:notice] = "スケジュールを登録しました"
      redirect_to plans_path
    else
      flash.now[:notice] = "スケジュールの登録に失敗しました"
      render "new"
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(schedule_params)
      flash[:notice] = "スケジュールを更新しました"
      redirect_to plans_path
    else
      flash.now[:notice] = "スケジュールの更新に失敗しました"
      render "edit"
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to plans_path
  end

  private

  def schedule_params
    params.require(:plan).permit(:title, :start_date, :finish_date, :all_day, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>スケジュール管理アプリ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/plans/edit.html.erb
<div class="container new-edit-container">

  <h2>予定を編集してください</h2>

  <% if flash[:notice] %>
    <p class="flash-new-edit"><%= flash[:notice] %></p>
  <% end %>

  <%= render 'shared/error', obj: @plan %>

  <div class="form">
    <%= form_with model: @plan do |f| %>
      <div class="form-group">
        <%= f.label :title, "タイトル", class: "required" %>
        <%= f.text_field :title, placeholder: "タイトル" %>
      </div>

      <div class="date-area">
        <div class="form-group date-form">
          <%= f.label :start_date, "開始日", class: "required" %>
          <%= f.date_field :start_date %>
        </div>
        <div class="form-group date-form">
          <%= f.label :finish_date, "終了日", class: "required" %>
          <%= f.date_field :finish_date %>
        </div>
      </div>

      <div class="form-group">
        <%= f.check_box :all_day %>
        <%= f.label :all_day, "終日の場合はチェックを入れます" %>
      </div>

      <div class="form-group">
        <%= f.label :memo, "スケジュールメモ" %>
        <%= f.text_area :memo, placeholder: "メモを入力する" %>
      </div>

      <div class="form-group button-area">
        <%= link_to "キャンセル", :plans, class: "btn btn-cancel" %>
        <%= f.submit "保存", class: "btn btn-save" %>
      </div>
    <% end %>
  </div>

</div>

app/views/plans/index.html.erb
<div class="container" id="index-container">

  <div class="table-header">
    <h2>予定一覧</h2>
    <%= link_to "＋新規追加", new_plan_path, class: "btn", id: "btn-new"  %>
  </div>

  <% if flash[:notice] %>
    <p id="flash-index"><%= flash[:notice] %></p>
  <% end %>

  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>終日</th>
        <th>更新日時</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @plans.each do |plan| %>
        <tr>
          <td><%= plan.id %></td>
          <td><%= plan.title %></td>
          <td><%= plan.start_date.strftime("%Y/%m/%d") %></td>
          <td><%= plan.finish_date.strftime("%Y/%m/%d") %></td>
          <td><%= "○" if plan.all_day %></td>
          <td><%= plan.updated_at.to_s(:datetime_jp) %></td>
          <td><%= link_to "詳細", plan_path(plan) %></td>
          <td><%= link_to "編集", edit_plan_path(plan) %></td>
          <td><%= link_to "削除", plan_path(plan), method: :delete, data: {confirm: "予定を削除しますか？"} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div id="table-footer">
    <div>
      予定合計 <span id="total-number"><%= @plans.count %></span>件
    </div>
    <div id="today-date">
      本日の日付 <%= @today %>
    </div>
  </div>

</div>

app/views/plans/new.html.erb
<div class="container new-edit-container">

  <h2>予定の新規追加</h2>

  <% if flash[:notice] %>
    <p class="flash-new-edit"><%= flash[:notice] %></p>
  <% end %>

  <%= render 'shared/error', obj: @plan %>

  <div class="form">
    <%= form_with model: @plan do |f| %>
      <div class="form-group">
        <%= f.label :title, "タイトル", class: "required" %>
        <%= f.text_field :title, placeholder: "タイトル" %>
      </div>

      <div class="date-area">
        <div class="form-group date-form">
          <%= f.label :start_date, "開始日", class: "required" %>
          <%= f.date_field :start_date %>
        </div>
        <div class="form-group date-form">
          <%= f.label :finish_date, "終了日", class: "required" %>
          <%= f.date_field :finish_date %>
        </div>
      </div>

      <div class="form-group">
        <%= f.check_box :all_day %>
        <%= f.label :all_day, "終日の場合はチェックを入れます" %>
      </div>

      <div class="form-group">
        <%= f.label :memo, "スケジュールメモ" %>
        <%= f.text_area :memo, placeholder: "メモを入力する" %>
      </div>

      <div class="form-group button-area">
        <%= link_to "キャンセル", :plans, class: "btn btn-cancel" %>
        <%= f.submit "保存", class: "btn btn-save" %>
      </div>
    <% end %>
  </div>

</div>

app/views/plans/show.html.erb
<div class="container" id="show-container">

  <p id="back-to-index"><%= link_to "← 一覧に戻る", :plans %></p>

  <div class="table-header">
    <h2><%= @plan.title %></h2>
    <%= link_to [:edit, @plan], class: "btn", id: "btn-edit" do %>
      <%= image_tag "pen.png" %> 編集
    <% end %>
  </div>

  <div id="table-show-container">
    <table class="table" id="table-show">
      <tr>
        <th>開始日</th>
        <td><%= @plan.start_date.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th>終了日</th>
        <td><%= @plan.finish_date.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th>終日</th>
        <td><%= "○" if @plan.all_day %></td>
      </tr>
      <tr>
        <th>スケジュールメモ</th>
        <td><%= @plan.memo %></td>
      </tr>
    </table>
  </div>

</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>